name: lint-js

on:
  push:
    paths:
      - "**/*.js"
      - ".github/workflows/lint-js.yml"
  pull_request:
    paths:
      - "**/*.js"
      - ".github/workflows/lint-js.yml"

permissions:
  contents: read

jobs:
  lint-js:
    name: lint (javascript)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install semistandard
        run: npm install -g semistandard

      - name: Run linter
        run: find . -name "*.js" -exec semistandard {} +
